### ISSUE TITLE
Name clash with python-axolotl package

### ISSUE THREAD

**Issue by wurstsalat3000** [axolotlauncher/axolotl#3]
Hi! Are you aware that there is a name conflict between `axolotl` and `python-axolotl` (1,2) packages?

Using `import axolotl.identitykey` gives a `ModuleNotFound` error if both packages are installed. This breaks packages using `python-axolotl`.

1. https://pypi.org/project/python-axolotl/
2. https://github.com/tgalal/python-axolotl

**Comment by naturecodevoid** [comment]
We may be able to change the imported module name, in the case we can't I think its pretty unlikely that both packages would be installed at the same time. Installing normally may also use a virtual environment, so this problem would only occur when they install using pypi/are using `axolotl` to make a launcher and they have `python-axolotl` installed.

**Comment by yonderbread** [comment]
Whoops! Sorry about that, we will try to resolve this naming conflict as soon as possible. We apologize for any inconveniences in the meanwhile. @wurstsalat3000
